### ISSUE TITLE
hide perpage selector

### ISSUE THREAD

**Issue by rhoit** [fiduswriter/Simple-DataTables#105]
Is there the option or method to hide (not create) per-page selector `.dataTable-dropdown` from `.dataTable-top`,
which could be achieved in original data table using [dom](https://datatables.net/reference/option/dom) option.

Currently I'm using css to resolve this issue is there the better way?
```css
.dataTable-dropdown {
    display: none;
}
```
