### ISSUE TITLE
Custom Styling/CSS/Markup?

### ISSUE THREAD

**Issue by tlorens** [fiduswriter/Simple-DataTables#76]
There's no docs for how to stylize the table headers, add sortable Icons, paginator, etc..

**Comment by lamualfa** [comment]
If you want to customize the Table style, just customize it from CSS with `.dataTable-table` as a selector. or if you want to customize a wider scope like Table Select, Table Search, Table Pagination, you can use `.dataTable-wrapper` for the selector.

**Example customize Table Search**

```css
.dataTable-wrapper .dataTable-search input {
     padding: 0.3rem .5rem;
     border: solid 1px black;
     border-radius: .25rem;
}
```
